export type AssetType = "ETF" | "Stock";

export type Instrument = {
  id: string;
  symbol: string;
  displaySymbol: string;
  name: string;
  country: string;
  exchange: string;
  currency: string;
  assetType: AssetType;
  dataKey: string;
  twelveDataSymbol?: string;
  twelveDataExchange?: string;
};

export const instruments = [
  {
    id: "voo",
    symbol: "VOO",
    displaySymbol: "VOO",
    name: "Vanguard S&P 500 ETF",
    country: "United States",
    exchange: "NYSE Arca",
    currency: "USD",
    assetType: "ETF",
    dataKey: "voo",
    twelveDataSymbol: "VOO",
    twelveDataExchange: "NYSE",
  },
  {
    id: "spy",
    symbol: "SPY",
    displaySymbol: "SPY",
    name: "SPDR S&P 500 ETF",
    country: "United States",
    exchange: "NYSE Arca",
    currency: "USD",
    assetType: "ETF",
    dataKey: "spy",
  },
  {
    id: "qqq",
    symbol: "QQQ",
    displaySymbol: "QQQ",
    name: "Invesco QQQ Trust",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "ETF",
    dataKey: "qqq",
  },
  {
    id: "aapl",
    symbol: "AAPL",
    displaySymbol: "AAPL",
    name: "Apple",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "aapl",
  },
  {
    id: "msft",
    symbol: "MSFT",
    displaySymbol: "MSFT",
    name: "Microsoft",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "msft",
  },
  {
    id: "nvda",
    symbol: "NVDA",
    displaySymbol: "NVDA",
    name: "NVIDIA",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "nvda",
  },
  {
    id: "amzn",
    symbol: "AMZN",
    displaySymbol: "AMZN",
    name: "Amazon",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "amzn",
  },
  {
    id: "meta",
    symbol: "META",
    displaySymbol: "META",
    name: "Meta Platforms",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "meta",
  },
  {
    id: "googl",
    symbol: "GOOGL",
    displaySymbol: "GOOGL",
    name: "Alphabet",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "googl",
  },
  {
    id: "tsla",
    symbol: "TSLA",
    displaySymbol: "TSLA",
    name: "Tesla",
    country: "United States",
    exchange: "Nasdaq",
    currency: "USD",
    assetType: "Stock",
    dataKey: "tsla",
  },
  {
    id: "brk-b",
    symbol: "BRK-B",
    displaySymbol: "BRK-B",
    name: "Berkshire Hathaway",
    country: "United States",
    exchange: "NYSE",
    currency: "USD",
    assetType: "Stock",
    dataKey: "brk-b",
  },
  {
    id: "jpm",
    symbol: "JPM",
    displaySymbol: "JPM",
    name: "JPMorgan Chase",
    country: "United States",
    exchange: "NYSE",
    currency: "USD",
    assetType: "Stock",
    dataKey: "jpm",
  },
  {
    id: "unh",
    symbol: "UNH",
    displaySymbol: "UNH",
    name: "UnitedHealth Group",
    country: "United States",
    exchange: "NYSE",
    currency: "USD",
    assetType: "Stock",
    dataKey: "unh",
  },
  {
    id: "cspx-l",
    symbol: "CSPX.L",
    displaySymbol: "CSPX.L",
    name: "iShares Core S&P 500 UCITS ETF",
    country: "Ireland / UCITS ETFs",
    exchange: "London Stock Exchange",
    currency: "USD",
    assetType: "ETF",
    dataKey: "cspx-l",
    twelveDataSymbol: "CSPXL",
    twelveDataExchange: "CBOE",
  },
  {
    id: "vwra-l",
    symbol: "VWRA.L",
    displaySymbol: "VWRA.L",
    name: "Vanguard FTSE All-World UCITS ETF",
    country: "Ireland / UCITS ETFs",
    exchange: "London Stock Exchange",
    currency: "USD",
    assetType: "ETF",
    dataKey: "vwra-l",
    twelveDataSymbol: "VWRA",
    twelveDataExchange: "LSE",
  },
  {
    id: "iwda-l",
    symbol: "IWDA.L",
    displaySymbol: "IWDA.L",
    name: "iShares Core MSCI World UCITS ETF",
    country: "Ireland / UCITS ETFs",
    exchange: "London Stock Exchange",
    currency: "USD",
    assetType: "ETF",
    dataKey: "iwda-l",
    twelveDataSymbol: "IWDA",
    twelveDataExchange: "LSE",
  },
  {
    id: "eimi-l",
    symbol: "EIMI.L",
    displaySymbol: "EIMI.L",
    name: "iShares Core MSCI EM IMI UCITS ETF",
    country: "Ireland / UCITS ETFs",
    exchange: "London Stock Exchange",
    currency: "USD",
    assetType: "ETF",
    dataKey: "eimi-l",
  },
  {
    id: "0050-tw",
    symbol: "0050.TW",
    displaySymbol: "0050.TW",
    name: "Yuanta Taiwan Top 50 ETF",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "ETF",
    dataKey: "0050-tw",
    twelveDataSymbol: "0050",
    twelveDataExchange: "TWSE",
  },
  {
    id: "0056-tw",
    symbol: "0056.TW",
    displaySymbol: "0056.TW",
    name: "Yuanta Taiwan High Dividend ETF",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "ETF",
    dataKey: "0056-tw",
    twelveDataSymbol: "0056",
    twelveDataExchange: "TWSE",
  },
  {
    id: "2330-tw",
    symbol: "2330.TW",
    displaySymbol: "2330.TW",
    name: "TSMC",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2330-tw",
  },
  {
    id: "2317-tw",
    symbol: "2317.TW",
    displaySymbol: "2317.TW",
    name: "Hon Hai Precision",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2317-tw",
  },
  {
    id: "2454-tw",
    symbol: "2454.TW",
    displaySymbol: "2454.TW",
    name: "MediaTek",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2454-tw",
  },
  {
    id: "2308-tw",
    symbol: "2308.TW",
    displaySymbol: "2308.TW",
    name: "Delta Electronics",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2308-tw",
  },
  {
    id: "2881-tw",
    symbol: "2881.TW",
    displaySymbol: "2881.TW",
    name: "Fubon Financial",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2881-tw",
  },
  {
    id: "2882-tw",
    symbol: "2882.TW",
    displaySymbol: "2882.TW",
    name: "Cathay Financial",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2882-tw",
  },
  {
    id: "2412-tw",
    symbol: "2412.TW",
    displaySymbol: "2412.TW",
    name: "Chunghwa Telecom",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2412-tw",
  },
  {
    id: "2303-tw",
    symbol: "2303.TW",
    displaySymbol: "2303.TW",
    name: "UMC",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2303-tw",
  },
  {
    id: "2891-tw",
    symbol: "2891.TW",
    displaySymbol: "2891.TW",
    name: "CTBC Financial",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "2891-tw",
  },
  {
    id: "3711-tw",
    symbol: "3711.TW",
    displaySymbol: "3711.TW",
    name: "ASE Technology Holding",
    country: "Taiwan",
    exchange: "Taiwan Stock Exchange",
    currency: "TWD",
    assetType: "Stock",
    dataKey: "3711-tw",
  },
  {
    id: "1155-kl",
    symbol: "1155.KL",
    displaySymbol: "1155.KL",
    name: "Maybank",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "1155-kl",
    twelveDataSymbol: "1155",
    twelveDataExchange: "MYX",
  },
  {
    id: "1023-kl",
    symbol: "1023.KL",
    displaySymbol: "1023.KL",
    name: "CIMB",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "1023-kl",
    twelveDataSymbol: "1023",
    twelveDataExchange: "MYX",
  },
  {
    id: "1295-kl",
    symbol: "1295.KL",
    displaySymbol: "1295.KL",
    name: "Public Bank",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "1295-kl",
    twelveDataSymbol: "1295",
    twelveDataExchange: "MYX",
  },
  {
    id: "5347-kl",
    symbol: "5347.KL",
    displaySymbol: "5347.KL",
    name: "Tenaga Nasional",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "5347-kl",
  },
  {
    id: "6947-kl",
    symbol: "6947.KL",
    displaySymbol: "6947.KL",
    name: "CelcomDigi",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "6947-kl",
  },
  {
    id: "6888-kl",
    symbol: "6888.KL",
    displaySymbol: "6888.KL",
    name: "Axiata",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "6888-kl",
  },
  {
    id: "2445-kl",
    symbol: "2445.KL",
    displaySymbol: "2445.KL",
    name: "Kuala Lumpur Kepong",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "2445-kl",
  },
  {
    id: "5819-kl",
    symbol: "5819.KL",
    displaySymbol: "5819.KL",
    name: "Hong Leong Bank",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "5819-kl",
  },
  {
    id: "5225-kl",
    symbol: "5225.KL",
    displaySymbol: "5225.KL",
    name: "IHH Healthcare",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "5225-kl",
  },
  {
    id: "3816-kl",
    symbol: "3816.KL",
    displaySymbol: "3816.KL",
    name: "MISC",
    country: "Malaysia",
    exchange: "Bursa Malaysia",
    currency: "MYR",
    assetType: "Stock",
    dataKey: "3816-kl",
  },
  {
    id: "es3-si",
    symbol: "ES3.SI",
    displaySymbol: "ES3.SI",
    name: "SPDR Straits Times Index ETF",
    country: "Singapore",
    exchange: "Singapore Exchange",
    currency: "SGD",
    assetType: "ETF",
    dataKey: "es3-si",
    twelveDataSymbol: "ES3",
    twelveDataExchange: "SGX",
  },
  {
    id: "g3b-si",
    symbol: "G3B.SI",
    displaySymbol: "G3B.SI",
    name: "Nikko AM Singapore STI ETF",
    country: "Singapore",
    exchange: "Singapore Exchange",
    currency: "SGD",
    assetType: "ETF",
    dataKey: "g3b-si",
  },
  {
    id: "d05-si",
    symbol: "D05.SI",
    displaySymbol: "D05.SI",
    name: "DBS Group",
    country: "Singapore",
    exchange: "Singapore Exchange",
    currency: "SGD",
    assetType: "Stock",
    dataKey: "d05-si",
  },
  {
    id: "o39-si",
    symbol: "O39.SI",
    displaySymbol: "O39.SI",
    name: "OCBC",
    country: "Singapore",
    exchange: "Singapore Exchange",
    currency: "SGD",
    assetType: "Stock",
    dataKey: "o39-si",
  },
  {
    id: "u11-si",
    symbol: "U11.SI",
    displaySymbol: "U11.SI",
    name: "UOB",
    country: "Singapore",
    exchange: "Singapore Exchange",
    currency: "SGD",
    assetType: "Stock",
    dataKey: "u11-si",
  },
  {
    id: "1306-t",
    symbol: "1306.T",
    displaySymbol: "1306.T",
    name: "NEXT FUNDS TOPIX ETF",
    country: "Japan",
    exchange: "Tokyo Stock Exchange",
    currency: "JPY",
    assetType: "ETF",
    dataKey: "1306-t",
  },
  {
    id: "7203-t",
    symbol: "7203.T",
    displaySymbol: "7203.T",
    name: "Toyota",
    country: "Japan",
    exchange: "Tokyo Stock Exchange",
    currency: "JPY",
    assetType: "Stock",
    dataKey: "7203-t",
  },
  {
    id: "6758-t",
    symbol: "6758.T",
    displaySymbol: "6758.T",
    name: "Sony Group",
    country: "Japan",
    exchange: "Tokyo Stock Exchange",
    currency: "JPY",
    assetType: "Stock",
    dataKey: "6758-t",
  },
  {
    id: "9984-t",
    symbol: "9984.T",
    displaySymbol: "9984.T",
    name: "SoftBank Group",
    country: "Japan",
    exchange: "Tokyo Stock Exchange",
    currency: "JPY",
    assetType: "Stock",
    dataKey: "9984-t",
  },
  {
    id: "8306-t",
    symbol: "8306.T",
    displaySymbol: "8306.T",
    name: "Mitsubishi UFJ Financial Group",
    country: "Japan",
    exchange: "Tokyo Stock Exchange",
    currency: "JPY",
    assetType: "Stock",
    dataKey: "8306-t",
  },
  {
    id: "2800-hk",
    symbol: "2800.HK",
    displaySymbol: "2800.HK",
    name: "Tracker Fund of Hong Kong",
    country: "Hong Kong",
    exchange: "Hong Kong Stock Exchange",
    currency: "HKD",
    assetType: "ETF",
    dataKey: "2800-hk",
    twelveDataSymbol: "2800",
    twelveDataExchange: "HKEX",
  },
  {
    id: "0700-hk",
    symbol: "0700.HK",
    displaySymbol: "0700.HK",
    name: "Tencent",
    country: "Hong Kong",
    exchange: "Hong Kong Stock Exchange",
    currency: "HKD",
    assetType: "Stock",
    dataKey: "0700-hk",
  },
  {
    id: "9988-hk",
    symbol: "9988.HK",
    displaySymbol: "9988.HK",
    name: "Alibaba",
    country: "Hong Kong",
    exchange: "Hong Kong Stock Exchange",
    currency: "HKD",
    assetType: "Stock",
    dataKey: "9988-hk",
  },
  {
    id: "0939-hk",
    symbol: "0939.HK",
    displaySymbol: "0939.HK",
    name: "China Construction Bank",
    country: "Hong Kong",
    exchange: "Hong Kong Stock Exchange",
    currency: "HKD",
    assetType: "Stock",
    dataKey: "0939-hk",
  },
  {
    id: "1299-hk",
    symbol: "1299.HK",
    displaySymbol: "1299.HK",
    name: "AIA Group",
    country: "Hong Kong",
    exchange: "Hong Kong Stock Exchange",
    currency: "HKD",
    assetType: "Stock",
    dataKey: "1299-hk",
  },
] satisfies Instrument[];

export const countryOptions = [
  ...new Set(instruments.map((instrument) => instrument.country)),
];

export const assetTypeOptions: AssetType[] = ["ETF", "Stock"];

export function getInstrumentById(id: string) {
  return instruments.find((instrument) => instrument.id === id);
}

export function getInstrumentsByMarketAndType(
  country: string,
  assetType: AssetType
) {
  return instruments.filter(
    (instrument) =>
      instrument.country === country && instrument.assetType === assetType
  );
}

export function getAssetTypesForMarket(country: string) {
  return assetTypeOptions.filter((assetType) =>
    instruments.some(
      (instrument) =>
        instrument.country === country && instrument.assetType === assetType
    )
  );
}
